### ISSUE TITLE
(Android) No implementation found for com.azure.communication.calling.status 

### ISSUE THREAD

**Issue by axelasarmiento** [Laerdal/Xamarin.AzureCommunicationCalling#10]
Hi @tompi, 

thank you so much for the new sample project using the NuGet packages

the iOS app is working great otherwise we are getting an error when we want to initialize the callingManager on Android _callingManager.Init(_token);
             
No implementation found for com.azure.communication.calling.status com.azure.communication.calling.NativeLibrary.sam_call_client_create(com.azure.communication.calling.Out) (tried Java_com_azure_communication_calling_NativeLibrary_sam_1call_1client_1create and Java_com_azure_communication_calling_NativeLibrary_sam_1call_1client_1create__Lcom_azure_communication_calling_Out_2)

We appreciate your help,

Thanks,
Axel

**Comment by tompi** [comment]
Hi. Not at my computer, but is this happening when debugging and linker options set to don’t link?

**Comment by axelasarmiento** [comment]
yes, I have tested using different linker options and also in release mode

**Comment by tompi** [comment]
I’ll check some devices tomorrow, but which device are you trying to debug on?

**Comment by axelasarmiento** [comment]
I have been testing on different physical devices such as Galaxy Note 8 and LG Q5 and emulator using android 9 and 10

**Comment by tompi** [comment]
@axelasarmiento Tested the app locally now, and didnt get any errors on initialization...
I assume this is not happening on the TestApp, but rather on your own app? Could you try adding an explicit reference to the "Xamarin.AzureCommunicationCommon.Android" and "Xamarin.AzureCore.Android" nugets? Also, if it crashes later on, compare to testapp nugets, I THINK you need to reference Square.OkHttp3 and Square.Retrofit2 as well, and for newer android version you need this in your android manifest(in "application"

```xml
<uses-library android:name="org.apache.http.legacy" android:required="false" />
```

**Comment by axelasarmiento** [comment]
I downloaded the TestApp project and I am getting the same error on the android side,
I verified the nugets you told me about but it is still showing the same message 

<img width="464" alt="Screen Shot 2020-12-02 at 12 33 32 PM" src="https://user-images.githubusercontent.com/73547980/100902409-3c3ae500-349b-11eb-8f77-5bc8acf3d474.png">

**Comment by tompi** [comment]
@axelasarmiento Could you check the ABI of your phones and emulators? (default for emulators are x86 I think which is not supported by ACS) .

To check ABI for your connected phone:
````
adb shell getprop ro.product.cpu.abi
```` 
ACS only supports x86_64 and arm64-v8a

**Comment by kagbakpem** [comment]
Thanks @tompi. @axelasarmiento, we currently only have support for x86_64 and arm64-v8a but will be providing support for the 32-bit ABI in our next release, so please stay tuned.
Re: your issue, if you figure out your issue is due to the unsupported ABI, let us know and we'll do our best to expedite the release if needed.

**Comment by axelasarmiento** [comment]
hi,

we tested it on a newer android device and it worked!

Thank you so much for your help!

**Comment by bigbbri** [comment]
Thanks @tompi for your help, we appreciate all of you.  Do you have an estimated date for the release that will support 32-bit ABI?

Thanks again,
Brian Adams
President, Ameliom IT LLC
A 30985 Oakview Rd Bulverde, TX 78163
M 210-452-1639
W www.ameliom.com

**Comment by kagbakpem** [comment]
@bigbbri, things keeps evolving so can't give a definitive timeline but it's reasonable to expect a drop by the EOY.

**Comment by tompi** [comment]
@bigbbri I'll keep this issue open, and close it once Microsoft releases 32 bit support and this binding lib is updated.

**Comment by tompi** [comment]
@bigbri 1.0.0-beta.5.1 should bring 32-bit support(and hence doubles the nuget size...)
