### ISSUE TITLE
Can you add live chat sample too

### ISSUE THREAD

**Issue by Sarthak261995** [Laerdal/Xamarin.AzureCommunicationCalling#13]
Great work first of all.
Can you add Chat and live notification sample too

**Comment by tompi** [comment]
@Sarthak261995 I just added what I needed in the sample. I checked quickstarts for ios and android, and they dont even have video calling in them... If Microsoft(or somebody else) makes samples for this; I should be able to add them here without too much trouble... At least for chat. Live notification requires Azure Notification Hub I think, so a bit work to setup...

Let me know if you figure it out yourself, and I will add your code as sample!

**Comment by WiproSarthak** [comment]
does this nuget include chat sdk also ? Or this is only for Video and Audio calling

**Comment by tompi** [comment]
@WiproSarthak Sorry, just video/audio for now. It wraps the "Calling" api, and since this uses the "Common" and "Core" apis from microsoft, they are also included.
