### ISSUE TITLE
Unable to get token. (Android)

### ISSUE THREAD

**Issue by CARP-Kaiser** [Laerdal/Xamarin.AzureCommunicationCalling#16]
Hello,

I think I must be misunderstanding something in the rest service. I am using my azure keys to fill out the Ip and ApiUrl fields.

For the Ip I am using the endpoint minus the prefix that you append for server. For the ApiUrl I have tried a few things including the primary key and the connection string separately. I had also tried putting a "/" at the and of the ApiUrl since the original example had shown it and I figured it might be used to separator in front of token for the var url. It is probably a misunderstanding on my side but I would like some advice on how to proceed.

**Comment by tompi** [comment]
Hey, sorry for the late reply, but this really isnt related to the library...

I would suggest that you start with getting the calling heros sample up and running:
https://docs.microsoft.com/en-us/azure/communication-services/samples/calling-hero-sample?pivots=platform-web

This backend is pretty similar to what the app expects.
You need to setup your own backend api that will generate ACS tokens, that is NOT part of my sample, and you will need to figure out that part separately... But as I said, the heros example from microsoft should get you started!

**Comment by CARP-Kaiser** [comment]
@tompi that is great news. Thanks for the heads up. I had thought it might be something like that after reading the api documentation.
