### ISSUE TITLE
Android: Video not shared in other device in group call

### ISSUE THREAD

**Issue by NeerajRai111** [Laerdal/Xamarin.AzureCommunicationCalling#17]
I am able to launch and test the android setup in multiple devices. I am able to generate the access token and start the group call. It launch the front camera of the device and the video is rendered on the same device but it in transmitting to other device.

If I debug the code, function _call_RemoteParticipantsUpdated(object sender, ParticipantsUpdatedEventArgs e) never called.

Can you please help to resolve this issue?

Thanks in advance!

I have just attached the screenshot of emulator but in real device I can only see my picture.
![image](https://user-images.githubusercontent.com/38005036/117626446-bd0db380-b194-11eb-9eda-9bac7a3cef88.png)

**Comment by tompi** [comment]
Sorry for late reply. Perhaps you could try a few things just to make sure everything is setup correctly:

1. You are generating different tokens for each device, right?
2. You are joining the same group(guid) on all devices?
3. Are you able to run the ACS web demo, and if so, can you try joining a group call from the mobile client?

**Comment by NeerajRai111** [comment]
Thanks Thomas for your response.

Initially, I was generating separate tokens but some how it was not working then I started using the same token.
Today, I again tried with the sperate token for the devices and it worked.

Apart from that, Do you have any reference for the text chat which could be utilized in Xamarin Forms APP.

Thanks

**Comment by tompi** [comment]
@NeerajRai111 The chat is bundled in a separate aar from microsoft: https://search.maven.org/search?q=a:azure-communication-chat for android and this one for ios: https://cocoapods.org/pods/AzureCommunicationChat

I never had any use for chat, so I never made a nuget for these, sorry...
