### ISSUE TITLE
iOS Native Linking failed

### ISSUE THREAD

**Issue by nielscup** [Laerdal/Xamarin.AzureCommunicationCalling#2]
Hi, thank you for sharing your bindings! I have a question regarding the iOS bindings: When I build the AzureCommunicationVideoTest.iOS I get about 40 errors like this one:  
`Error MT5211: Native linking failed, undefined Objective-C class: ACSCall. The symbol '_OBJC_CLASS_$_ACSCall' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (AzureCommunicationVideoTest.iOS)`

I have installed Git LFS and I see 3 native references in the Xamarin.AzureCommunicationCalling.iOS project:

1. AzureCore
1. AzureCommunication
1. AzureCommunicationCalling

Is the big native reference you mention in the readme one of the above, or do I need to add another one?

**Comment by tompi** [comment]
Hi @nielscup . Are you building for a real device? I suspect you will get this error trying to build for the simulator...

**Comment by nielscup** [comment]
Problem was that I downloaded the code zip. That does not work because of LFS. You need to clone the code and pull to retrieve the file from LFS.
