### ISSUE TITLE
How to do direct video call?

### ISSUE THREAD

**Issue by MhAllan** [Laerdal/Xamarin.AzureCommunicationCalling#20]
I can't see how to do a video call to one user. I see call to a group only, and I don't know where does the group id come from. could you please ad some documentation

**Comment by tompi** [comment]
Hi @MhAllan 

This is just a wrapper for Microsoft APIs, so check out their documentation here:

ios: https://docs.microsoft.com/en-us/objectivec/communication-services/calling/
android: https://docs.microsoft.com/en-us/java/api/com.azure.android.communication.calling?view=communication-services-java-android

**Comment by tompi** [comment]
Oh, and the group id is just a random Guid, you can just make up whatever you want

**Comment by MhAllan** [comment]
Thanks for quick reply @tompi . I am looking for this piece of code

```csharp
call = callAgent.startCall(
            context,
            participants,
            options);
```

found here: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-android

but CallAgent of your wrapper doesn't have such a method

**Comment by tompi** [comment]
@MhAllan You are correct, my binding is currently stuck on beta-7, until I figure out a workaround for #18 

On beta-7 the same method was called "Call". Try using that!

**Comment by MhAllan** [comment]
Thanks @tompi, I will try that. re #18 if you have branch with all new dependencies ready please share it so we can try our luck XD. I only see master
