### ISSUE TITLE
Android device freezes when calling hangup method

### ISSUE THREAD

**Issue by SeadnaS** [Laerdal/Xamarin.AzureCommunicationCalling#22]
I have a hangup method which causes the app to hang every time. It hangs at the _call.Hangup() line and no exception is thrown:

```
public async Task Hangup()
        {
            if (_call == null)
                return;

            try
            {
                _call.RemoteParticipantsUpdated -= _call_RemoteParticipantsUpdated;
                var hangupOptions = new HangupOptions();
                await _call.Hangup(hangupOptions).GetAsync();
                Dispose();
            }
            catch
            {
                throw new Exception("Something went wrong when ending the call");
            }
        }
```

LogCat:

> 07-09 13:33:49.198: E/ActivityManager(1279): ANR in com.laerdal.azurecommunicationvideotest (com.laerdal.azurecommunicationvideotest/crc64cf23a0a2815e40d5.MainActivity)
> 07-09 13:33:49.198: E/ActivityManager(1279): Parent: com.laerdal.azurecommunicationvideotest/crc64cf23a0a2815e40d5.MainActivity
> 07-09 13:33:49.198: E/ActivityManager(1279):   0.6% 12649/com.laerdal.azurecommunicationvideotest: 0.1% user + 0.5% kernel / faults: 706 minor
> 07-09 13:33:49.372: E/InputDispatcher(1279): channel '88a0a1c com.laerdal.azurecommunicationvideotest/crc64cf23a0a2815e40d5.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

Any ideas what is happening or how to proceed fixing it?

**Comment by tompi** [comment]
I’m not sure, but is my example app working or is the hangup causing a crash on your device as well?

if it works, you might just check if get instead of getasync works on the hangup method.

**Comment by SeadnaS** [comment]
Hmm it seems to be fixed by removing the .GetAsyc()

**Comment by tompi** [comment]
@SeadnaS I have an idea of whats happening, if hangup takes too long, and you are awaiting it on the UI thread, you would most likely get an ANR. This report indicates hangups take a while on android:
 
https://github.com/Azure/Communication/issues/339
