### ISSUE TITLE
When local camera preview renders other sounds of the app become low volume

### ISSUE THREAD

**Issue by MhAllan** [Laerdal/Xamarin.AzureCommunicationCalling#24]
I am trying to do this, when I call and before the other side joins, I want to show the camera preview and play out ringing sound. the sound starts good but once the camera preview renders (before streaming out my camera through the call and before participants joins so it has nothing to do with ACS I suppose) the sound dims and can't be increased to it's normal volume.

I am using this for playing the sound: https://github.com/adrianstevens/Xamarin-Plugins/tree/master/SimpleAudioPlayer

**Comment by MhAllan** [comment]
I think it is intended behaviour to lower the media and increate call volume

**Comment by tompi** [comment]
@MhAllan I think you are right about this being done "on purpose" by ACS, but I think you can still work around it by setting different sound profiles manually, e.g. you could find out where ACS sets the sound profile to some sort of communication, and then manually override to "media" so your ringer plays, and then hook up an event handler to connection state changed for acs and change profile to voice/video there...
