### ISSUE TITLE
[iOS] 15.5 build failed _CollectFrameworks

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Laerdal/Xamarin.AzureCommunicationCalling#27]
We are experiencing an issue in your example when running on an iOS 15.5 device: Target "_CollectFrameworks" does not exist in the project
Any idea what this problem is about?

**Comment by tompi** [comment]
Sorry about the late reply, but not sure about this...

Is it happening in debug mode also? Or just release?
(gut feeling says linker issue... Could you try link none?)

Also, is same build/ide working on another phone?

Also, which physical device is this?

**Comment by andersonvieiragomeslopes** [comment]
> Sorry about the late reply, but not sure about this...
> 
> Is it happening in debug mode also? Or just release? (gut feeling says linker issue... Could you try link none?)
> 
> Also, is same build/ide working on another phone?
> 
> Also, which physical device is this?
> 
> BTW: I just tested upgrading my device to 15.5, and it still worked here...

Thanks for the answer.

We are using it in debug mode on an iphone 8 plus physical device, but it doesn't work on emulators either. Do you have a local file that hasn't been uploaded to the repository?
I tested the 3 linker options but I was not successful in any, I also created a linker.xml file to set the classes but without success.

You can try to simulate the problem by adding the nuget in a blank project and trying to build it, it was a little easy to detect the problem here in my environment.

I don't know exactly if it's valid, but out of curiosity, I tested it in the TestApp project but without success.
`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

**Comment by tompi** [comment]
Im using the nuget in 2 different apps built in appcenter so im pretty confident it works outside my machine ;)

You are using visual studio 19?
If you do a git status in your repo folder, does it show "working tree clean" ?

**Comment by andersonvieiragomeslopes** [comment]
I'm using visual studio 2022 and visual studio 2022 preview, I'm going to download 2019 to check if it works and I'm in windows/macOS environment on both the problem occurs, direct debug on macOS and remote debug windows on macOS.

> If you do a git status in your repo folder, does it show "working tree clean" ?

Yes, the only changes I made were the development credentials to debug on a physical device with id authorized in the development key. But it was very easy to notice the problem as when I added nuget in another project the same error appeared.

**Comment by tompi** [comment]
I dont think 2022 is released for mac yet?

Last time I tried using it things started breaking bad pretty quickly...

I probably wont spend time making it work there until 2022 makes it into the appcenter/devops images.

**Comment by andersonvieiragomeslopes** [comment]
> I dont think 2022 is released for mac yet?

Yes
![image](https://user-images.githubusercontent.com/26186056/169906013-5b8b654e-e8b5-4b0b-bb03-6e5f07130d20.png)


Update: Finally I managed to install it on an emulator, but the physical device still has the same problem, what is curious is that the error persists and there are failures in attempts to install the emulator, it is necessary to insist to be able to install.

**Comment by jveenhuizen** [comment]
Hi!

I also experience the same problem when installing the nuget package for iOS. Both at visual studio 2019 and 2022 and both on a physical device (iPhone 13 mini) as a simulator. iOS sdk version 15.5. I also remember getting this error sometime last week on 15.4. Is there anything I can do to get this working or to help?

**Comment by andersonvieiragomeslopes** [comment]
@jveenhuizen  If the problem is with the packaging I believe just generate a new local nuget and add it to the project, when things started to go bad in visual studio 2022 do you remember the exact reason @tompi ? I'm assuming it's something simple to solve in nuget packaging.

**Comment by jveenhuizen** [comment]
The build output:

```
/Users/jordyveenhuizen/.nuget/packages/xamarin.swift/1.0.8/build/xamarinios/Xamarin.Swift.targets(33,135): error MSB4057: The target "_CollectFrameworks" does not exist in the project.
    72 Warning(s)
    1 Error(s)

Time Elapsed 00:00:15.87
```

This is the package i'm installing:

![Schermafbeelding 2022-05-24 om 14 47 22](https://user-images.githubusercontent.com/88036760/170038111-b64da3a4-38cc-4d4e-aa1f-28be1e28edf0.png)

And everything is up to date with my visual studio & xcode.

![Schermafbeelding 2022-05-24 om 14 50 12](https://user-images.githubusercontent.com/88036760/170038685-7f0d455a-abed-4a3a-9e57-bb4dc0acbd10.png)

Visual studio version:

![Schermafbeelding 2022-05-24 om 14 51 34](https://user-images.githubusercontent.com/88036760/170038991-698692fa-c603-4526-bd97-b079fb3da834.png)

**Comment by tompi** [comment]
When I think about it, I probably should not declare a dependency on xamarin.swift, and just let people use their own, especially since microsoft has a nuget for this(even though i never managed to get it working...)

I will try to publish a version without this dep.
(you probably wont even need it if you target a platform with swift bundled, ios 12.2 i think)

**Comment by jveenhuizen** [comment]
Deleted .vs / bin / obj files and used vs 2019. Stil the same issue.. :-(

**Comment by andersonvieiragomeslopes** [comment]
@tompi i'm guessing there is some breaking change from microsoft.
Do you believe this problem is related? https://github.com/xamarin/xamarin-macios/issues/14203

I formatted macOS last Sunday thinking it was local :( but unfortunately the problem persisted.
I can't find visual studio 2019 for mac, strangely it doesn't show up on the download page for previous microsoft versions.

**Comment by jveenhuizen** [comment]
@tompi I'm using the vs nuget manager. Highest version there is 1.1.0.4 (see screenshot above)

**Comment by andersonvieiragomeslopes** [comment]
> @tompi I'm using the vs nuget manager. Highest version there is 1.1.0.4 (see screenshot above) Edit: "include prerelease" checkbox wasn't checked. My bad. Installing now.

Do you you need to enable nuget previews. 
These latest most up-to-date versions are in beta status.

**Comment by andersonvieiragomeslopes** [comment]
I was able to install on a physical device now!!!!!!!!!!!!!!!
