### ISSUE TITLE
DisplayName missing on Android

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Laerdal/Xamarin.AzureCommunicationCalling#28]
Could you add one more parameter to be able to define a name for the user? is that it currently does not display the participant's name on android due to the absence of this item.

Your Code : https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/blob/5ce72cd83977fc5ee8b0b37380745b561112a8e4/Bindings/Android/AzureCommunicationCallingHelper/src/main/java/com/laerdal/azurecommunicationhelper/CallClientHelper.java#L24

Microsoft implementation: https://github.com/Azure-Samples/communication-services-android-calling-hero/blob/378e313d93626fd5b71736b24fac89e24a50038b/AzureCalling/app/src/main/java/com/azure/samples/communication/calling/external/calling/CallingContext.java#L421

`final CallAgentOptions options = new CallAgentOptions();
            options.setDisplayName(userName);`
            
I believe this is a simple modification, but it may be necessary to make this property nullable so as not to break the project if the user runs the test app without entering this information.

The property to create and inform is already available, so it was only missing in `(appContext, communicationUserCredential, options)`

**Comment by tompi** [comment]
sorry, busy with other stuff, but will make a release this week. I assume exposing the options param is the best approach, should be future proof if they add more stuff

**Comment by andersonvieiragomeslopes** [comment]
@tompi Thanks, the next android/iOS versions are full of improvements :) when you publish let me know, please.

**Comment by tompi** [comment]
@andersonvieiragomeslopes  just published 2.2.0 and new version of helper to allow setting display name.
upgrade to helper 2.2.0 and see this commit for how to set display name:
 
https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/commit/fab930bae34f9116497b1a9dec0b5fc3ed6ddde0#diff-27d724e536872911fd95f7915b2072ea284b94eb2e4f3dad12308a69ab31707e

will release 2.3 beta shortly

**Comment by andersonvieiragomeslopes** [comment]
> @andersonvieiragomeslopes just published 2.2.0 and new version of helper to allow setting display name. upgrade to helper 2.2.0 and see this commit for how to set display name:
> 
> [fab930b#diff-27d724e536872911fd95f7915b2072ea284b94eb2e4f3dad12308a69ab31707e](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/commit/fab930bae34f9116497b1a9dec0b5fc3ed6ddde0#diff-27d724e536872911fd95f7915b2072ea284b94eb2e4f3dad12308a69ab31707e)
> 
> will release 2.3 beta shortly

It works perfectly, thanks.
