### ISSUE TITLE
[Feature] PushNotification Android

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Laerdal/Xamarin.AzureCommunicationCalling#33]
Hi, again.

I noticed that there is a lack of implementations for the push function on android, I did some tests here and I believe that this is the fix based on the official documentation/example.

[Official example](https://docs.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/push-notifications?pivots=platform-android)

```
public static void RegisterPushNotification(CallAgent callAgent, String deviceRegistrationToken) throws ExecutionException, InterruptedException {
        callAgent.registerPushNotification(deviceRegistrationToken).get();
    }
public static void UnRegisterPushNotification(CallAgent callAgent) throws ExecutionException, InterruptedException {
        callAgent.unregisterPushNotification().get();
    }
public static void HandlePushNotification(CallAgent callAgent, PushNotificationInfo pushNotificationInfo) throws ExecutionException, InterruptedException {
        callAgent.handlePushNotification(pushNotificationInfo);
    }
```

**Comment by andersonvieiragomeslopes** [comment]
@tompi Can you help with this item? This is really necessary so that the user can answer the cell phone with the screen off, I intend to do 3 more PR with items that are still missing from the list.

**Comment by tompi** [comment]
@andersonvieiragomeslopes please check if [2.3.0-beta.1.6](https://www.nuget.org/packages/Xamarin.AzureCommunicationCallingHelper.Android/2.3.0-beta.1.6) 
works as intended

**Comment by andersonvieiragomeslopes** [comment]
@tompi I think something went wrong with the plugin, the methods are not there.

![image](https://user-images.githubusercontent.com/26186056/183133310-81bfb1c3-fcca-4f32-bf10-0ee528f34bc8.png)

**Comment by tompi** [comment]
@andersonvieiragomeslopes  ooops, sorry, not sure what went wrong, should have tested...
[2.3.0-beta.1.6](https://www.nuget.org/packages/Xamarin.AzureCommunicationCallingHelper.Android/2.3.0-beta.1.7)
should fix it
