### ISSUE TITLE
Android video streaming issue

### ISSUE THREAD

**Issue by aodegov** [Laerdal/Xamarin.AzureCommunicationCalling#35]
### Issue prerequisites 
___

1. Used [TestSample project](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/tree/master/TestSample)

2. All functionality in the `TestSample` according to [latest commit](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/commit/c8b1dc3d5c2c8abf3b30a6cba16a6896f9a05e76), for this time (24th of August 2022)

3. Tested on real devices:
    **Android**: Huawei P20 pro  
    **iOS**: iPhone 12 Pro

4. Call mode (or TypeCall): **Group** call

### Issue description
___ 

- Video stream from Android device is not working correctly.
   I can't see the video on my iPhone from Android user phone, when I have the Group call.
   However, the iOS video stream is working correctly. 
   I can see my iOS video (or user video) on Android user's device.

Please help to solve this issue, or fix this if it possible.
Thanks.

**Comment by andersonvieiragomeslopes** [comment]
Hello @aodegov.

Sorry, I believe this issue went unnoticed due to the high amount of items that were provided in the example, don't worry, I'll fix it tomorrow.

**Comment by andersonvieiragomeslopes** [comment]
Hello @aodegov.

The fixes have been submitted, it's small details, you can easily capture it so you don't have to wait too long.

**Comment by aodegov** [comment]
> Hello @aodegov.
> 
> The fixes have been submitted, it's small details, you can easily capture it so you don't have to wait too long.
> 

Thanks @andersonvieiragomeslopes , I'll take a look.

**Comment by aodegov** [comment]
@andersonvieiragomeslopes, I've checked your latest changes.
Thanks, in general looks better.
But there are steel several issues with video.
Please see my newest ticket: #37 
And I'll close this one, hopefully @tompi doesn't mind )
