### ISSUE TITLE
Update libraries Android (2.5.0-beta.1) and iOS (2.3.0.beta-2)

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Laerdal/Xamarin.AzureCommunicationCalling#43]
Hello @tompi.

Finally screen sharing has arrived on iOS, as soon as the nuget version is available I will implement it for iOS.

https://github.com/Azure/Communication/releases

**Comment by tompi** [comment]
@andersonvieiragomeslopes updated nugets now. Let me know if you are missing something.

P.S. checked on the binding generated class parser file for android, so its easier to see which new methods I should add in the helper lib

**Comment by andersonvieiragomeslopes** [comment]
Thanks @tompi.

https://github.com/Azure/azure-sdk/issues/4373

![image](https://user-images.githubusercontent.com/26186056/201131545-edf14f63-23e0-4964-a4a8-30bf23ed75d6.png)


System audio sharing is also available, I will analyze and send you the necessary methods to add to the communication helper.

**Comment by tompi** [comment]
@andersonvieiragomeslopes as long as its not a Future, it should be available in the regular lib. 

Its only the futures that are not caught by the binding lib.

**Comment by andersonvieiragomeslopes** [comment]
Hi @tompi. 

![image](https://user-images.githubusercontent.com/26186056/201340462-c44ee258-c480-49f1-8932-84b206ecf2f5.png)

Maybe, this audio sharing api has been renamed, I didn't find it here and it seems that they put it inside this element (Call) as mentioned in this little code in the ticket above.

**Comment by andersonvieiragomeslopes** [comment]
Hi @tompi 

[This ACSRoomCallLocator ](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/blob/b4489128a64c56d1f5ec28c910f39b02088fa9f2/Bindings/Xamarin.AzureCommunicationCalling.iOS/ApiDefinitions.cs#L2069) It doesn't inherit from communication I think we have a problem with rooms support without this inheritance. 

[Please check it here. ](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/blob/b4489128a64c56d1f5ec28c910f39b02088fa9f2/Bindings/Xamarin.AzureCommunicationCalling.iOS/ApiDefinitions.cs#L1360)
