### ISSUE TITLE
Any plans for MAUI?

### ISSUE THREAD

**Issue by MhAllan** [Laerdal/Xamarin.AzureCommunicationCalling#48]
Any plans to make this available for MAUI? maybe you can reach Microsoft they will love it as their example is terrible and incomplete.

**Comment by andersonvieiragomeslopes** [comment]
> Any plans to make this available for MAUI? maybe you can reach Microsoft they will love it as their example is terrible and incomplete.


Hello, @MhAllan.

The migration it's in progress, but have problems with dotnet maui, maybe with dotnet seven it works.

@tompi can we resume the migration? Here at the company, we are going to start the migration, can you generate the android/ios nuget again for testing? The sample app stays with me.

**Comment by tompi** [comment]
@andersonvieiragomeslopes Sorry, I just tried once more, and the bindings generator still crash with same message:

```
BINDINGSGENERATOR : error BG0000: System.NullReferenceException: Object reference not set to an instance of an object. [/Users/tompi/src/Xamarin.AzureCommunicationCalling/Bindings/Android/Laerdal.Maui.          AzureCommunicationCommon.Android/Laerdal.Maui.AzureCommunicationCommon.      Android.csproj::TargetFramework=net7.0-android]
```

Not sure how to proceed, no useful error message, and no relevant google hits...

Should maybe report a bug somewhere, but Im guessing Maui team have a lot to do, and this is probably very low pri for them... I still think Maui is far from production ready unfortunately...

**Comment by andersonvieiragomeslopes** [comment]
Hi @tompi .

We don't have choice and time.
Android 14 and iOS 17 will not be supported unfortunately. 

Could you check the iOS migration while I check if I get results with Android?


![image](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/assets/26186056/f1454475-a3c3-4c8d-b576-1c474f898020)
https://devblogs.microsoft.com/xamarin/xamarin-ios-16-android-13-updates/

**Comment by tompi** [comment]
I started today, but lots of meetings, will try to get it done on monday.

Aiming for 2.3.0-beta.5, since 2.3.0 is missing a lot from the 2.3.0-beta...

Anyway, we should have another year of xamarin at least, but I agree its best to get started...

**Comment by tompi** [comment]
@andersonvieiragomeslopes I tried updating the iOS binding library for Maui(.net 6) to 2.3.0-beta.5.

There were actually a lot of changes between beta.4 and beta.5...

Anyway, I dont have much time trying to validate this on Maui, let me know if you run into problems or anything seems off(there were some depracations of muting functionality, but should be straightforward to use new methods).

P.S. Any luck on the Android bindings?

**Comment by tompi** [comment]
@andersonvieiragomeslopes Hey, curious about the status of this... Did you have any success binding the android lib for Maui?

**Comment by andersonvieiragomeslopes** [comment]
Hi @tompi.

Sorry, I'm traveling these last few days.

**Comment by andersonvieiragomeslopes** [comment]
Hi @tompi.

I am back. At the end of the week I go back to the migration stage with android to see if I can solve the problem.

**Comment by andersonvieiragomeslopes** [comment]
Hello @tompi @MhAllan 

I believe I have the same problem as you.
However, I have my time almost at the limit, I will dedicate an exclusive time to try to solve this as soon as possible later this week, I'll give you news.  

![image](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/assets/26186056/a51b65ad-ccd6-480e-a988-3bca46a6fe3b)

**Comment by tompi** [comment]
We now have functioning maui nugets. Still missing ports for the example app, but not sure we will prioritize this, what do you think @andersonvieiragomeslopes ?

**Comment by andersonvieiragomeslopes** [comment]
> We now have functioning maui nugets. Still missing ports for the example app, but not sure we will prioritize this, what do you think @andersonvieiragomeslopes ?

Of course, I'll look at how the nugget packages are doing and start migrating the example app
