### ISSUE TITLE
AzureCore.AzureError.sdk("Token is not formatted correctly.", nil)

### ISSUE THREAD

**Issue by axesar** [Laerdal/Xamarin.AzureCommunicationCalling#5]
Hi!

When I call await_callingManager.Init(_token); the response is "Token is not formatted correctly."

I am serializing an AzureCommunicationToken object to JSON 

There is a special format for the token?

I would appreciate your help.

Thanks!

**Comment by tompi** [comment]
You should just provide the token itself, not json. I can give you an example tomorrow when im at my desk

**Comment by bigbbri** [comment]
Thanks for replying, we got it!
B

**Comment by tompi** [comment]
Assuming you figured it out, feel free to reopen if its still not working
