### ISSUE TITLE
Speaker, mic and camera toggle

### ISSUE THREAD

**Issue by axelasarmiento** [Laerdal/Xamarin.AzureCommunicationCalling#6]
Hi,

We've been using the new nuget package and it works fantastically!

We wonder if there a property exists to use speakers, mute the mic and turn off the camera

Thank you!

**Comment by bigbbri** [comment]
The speaker default on iOS is the ear but we’d like to use the larger
speakers.  Is there a way to toggle that?
We see isMutedMic but we didn’t find a way to call for Mute toggling.
Same for the camera.


Thanks!!
Brian

**Comment by tompi** [comment]
Hey, I really havent explored this much as default options have worked for me. I see that web and mobile sdks differ on this point. In the web sdk, the audioOptions have settable "speakers" and "microphone", but ios and android do NOT have these. Perhaps @raosanat knows if they are coming?

The mobile sdks DO HAVE a way of getting a list of mics and speakers from the device manager, and I see there is attributes on the deviceManager called "microphone" and "speakers", so you could try setting these to something from the list and see if it works. Would be strange if the sdk differed like this though...

As to muting: this is done on the call itself, there is a "mute()" method and "unmute()".
If you want to stop/start video you can do that by retaining the renderer.

**Comment by mariusu-msft** [comment]
Hi,

At this time for mobile, we are planning to remove the audio devices functionality from DeviceManager.

To switch between AudioDevices, please use `AVFundation` directly.

Something like this:
```c#
AVFoundation.AVAudioSession.SharedInstance().OverrideOutputAudioPort(AVFoundation.AVAudioSessionPortOverride.Speaker
```

https://docs.microsoft.com/en-us/dotnet/api/avfoundation.avaudiosession.overrideoutputaudioport?view=xamarin-ios-sdk-12#AVFoundation_AVAudioSession_OverrideOutputAudioPort_AVFoundation_AVAudioSessionPortOverride_Foundation_NSError__

Thanks,
Marius

**Comment by tompi** [comment]
Closing this since @mariusu-msft seems to have answered the audio speaker toggle and I think I answered the muting/stop camera question

**Comment by axelasarmiento** [comment]
Hi @tompi! 

I've been looking for the mute() and unmuted() methods but I am not able to see them in the objects, 

could you explain a little bit more about where exactly the methods are and where to call them,

thanks!

**Comment by tompi** [comment]
@axelasarmiento When you start a call you should get an instance of the ACSCall class. This has two methods you can use: MuteWithCompletionHandler and UnmuteWithCompletionHandler
